import React, { ReactElement } from "react";
import { DashboardIcon } from "../icons/DashboardIcon";
import { RepertoireIcon } from "../icons/RepertoireIcon";
import { CalendarIcon } from "../icons/CalendarIcon";
import { DatabaseIcon } from "../icons/DatabaseIcon";
import { UsersIcon } from "../icons/UsersIcon";
import { SparklesIcon } from "../icons/SparklesIcon";
import { BookOpenIcon } from "../icons/BookOpenIcon";
import { TagIcon } from "../icons/TagIcon";
import { MusicNoteIcon } from "../icons/MusicNoteIcon";
import { SuggestionIcon } from "../icons/SuggestionIcon";
import { ClipboardListIcon } from "../icons/ClipboardListIcon";
import { StoreIcon } from "../icons/StoreIcon";
import { SettingsIcon } from "../icons/SettingsIcon";
import { UserIcon } from "../icons/UserIcon";
import { KeyPermissionsIcon } from "../icons/KeyPermissionsIcon";
import { CloudArrowUpIcon } from "../icons/CloudArrowUpIcon";
import { BugIcon } from "../icons/BugIcon";
import { BookTextIcon } from "../icons/BookTextIcon";
import { MessageSquareQuestionIcon } from "../icons/MessageSquareQuestionIcon";
import { ShieldAlert, FileText } from "lucide-react";
import { ChordsIcon } from "../icons/ChordsIcon";
import { HelpCircleIcon } from "../icons/HelpCircleIcon";

export interface NavigationItem {
  id: string;
  type: "link" | "group_trigger" | "action";
  icon: ReactElement | null;
  labelKey: string;
  defaultLabel: string;
  path?: string;
  permissionRequired: string | null;
  section: "primary" | "admin" | "help";
  group: string | null;
  collapseToDirectWhenSingleChild?: boolean;
}

export const navigationRegistry: NavigationItem[] = [
  // --- SEÇÃO PRINCIPAL ---
  {
    id: "dashboard",
    type: "link",
    icon: <DashboardIcon />,
    labelKey: "nav.dashboard",
    defaultLabel: "Painel",
    path: "/",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: null,
  },
  {
    id: "repertoire",
    type: "group_trigger",
    icon: <RepertoireIcon />,
    labelKey: "nav.repertoire",
    defaultLabel: "Repertório",
    path: "/songs",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: null,
  },
  {
    id: "songs",
    type: "link",
    icon: <MusicNoteIcon />,
    labelKey: "nav.songs",
    defaultLabel: "Músicas",
    path: "/songs",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "repertoire",
  },
  {
    id: "chords",
    type: "link",
    icon: <ChordsIcon />,
    labelKey: "nav.chords",
    defaultLabel: "Cifras",
    path: "/chords",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "repertoire",
  },
  {
    id: "lyrics",
    type: "link",
    icon: <FileText className="w-4 h-4 opacity-70" strokeWidth={2} />,
    labelKey: "nav.lyrics",
    defaultLabel: "Letras",
    path: "/lyrics",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "repertoire",
  },
  {
    id: "scales",
    type: "group_trigger",
    icon: <CalendarIcon />,
    labelKey: "nav.scales",
    defaultLabel: "Escalas",
    path: "/scales",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: null,
  },
  {
    id: "music_scales",
    type: "link",
    icon: <ClipboardListIcon />,
    labelKey: "nav.my_scales",
    defaultLabel: "Escalas de Músicas",
    path: "/scales",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "scales",
  },
  {
    id: "band_scales",
    type: "link",
    icon: <CalendarIcon />,
    labelKey: "nav.band_scales",
    defaultLabel: "Escalas da Banda",
    path: "/band-scales",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "scales",
  },
  {
    id: "library",
    type: "group_trigger",
    icon: <BookOpenIcon />,
    labelKey: "nav.library",
    defaultLabel: "Biblioteca",
    path: "/library",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: null,
    collapseToDirectWhenSingleChild: true,
  },
  {
    id: "viva_library",
    type: "link",
    icon: <BookOpenIcon />,
    labelKey: "nav.viva_title",
    defaultLabel: "Biblioteca Viva",
    path: "/library",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "library",
  },
  {
    id: "curation_queue",
    type: "link",
    icon: <ClipboardListIcon />,
    labelKey: "nav.curation_queue",
    defaultLabel: "Curadoria",
    path: "/curation",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: "library",
  },
  {
    id: "band",
    type: "link",
    icon: <UsersIcon />,
    labelKey: "nav.band",
    defaultLabel: "Integrantes",
    path: "/band",
    permissionRequired: "musicscale.members.manage",
    section: "primary",
    group: null,
  },
  {
    id: "updates",
    type: "link",
    icon: <SparklesIcon />,
    labelKey: "nav.updates",
    defaultLabel: "Novidades",
    path: "action:whatsnew",
    permissionRequired: "musicscale.performance.use",
    section: "primary",
    group: null,
  },

  // --- SEÇÃO ADMINISTRAÇÃO ---
  {
    id: "structures",
    type: "group_trigger",
    icon: <DatabaseIcon />,
    labelKey: "nav.structures",
    defaultLabel: "Configuração do ministério",
    path: "/database",
    permissionRequired: null,
    section: "admin",
    group: null,
  },
  {
    id: "overview",
    type: "link",
    icon: <DatabaseIcon />,
    labelKey: "nav.database",
    defaultLabel: "Dados da igreja",
    path: "/database",
    permissionRequired: "manageOrganization",
    section: "admin",
    group: "structures",
  },
  {
    id: "types_events",
    type: "link",
    icon: <CalendarIcon />,
    labelKey: "nav.types_events",
    defaultLabel: "Tipos de culto e evento",
    path: "/database#types",
    permissionRequired: "manageTaxonomy",
    section: "admin",
    group: "structures",
  },
  {
    id: "locations",
    type: "link",
    icon: <TagIcon />,
    labelKey: "nav.locations_title",
    defaultLabel: "Locais",
    path: "/database#locations",
    permissionRequired: "manageTaxonomy",
    section: "admin",
    group: "structures",
  },
  {
    id: "event_names",
    type: "link",
    icon: <TagIcon />,
    labelKey: "nav.event_names_title",
    defaultLabel: "Nomes de evento",
    path: "/database#event-names",
    permissionRequired: "manageTaxonomy",
    section: "admin",
    group: "structures",
  },
  {
    id: "tags_categories",
    type: "link",
    icon: <TagIcon />,
    labelKey: "nav.tags_categories",
    defaultLabel: "Tags & Categorias",
    path: "/database#tags",
    permissionRequired: "manageTaxonomy",
    section: "admin",
    group: "structures",
  },
  {
    id: "skills",
    type: "link",
    icon: <MusicNoteIcon />,
    labelKey: "nav.skills",
    defaultLabel: "Habilidades",
    path: "/database#skills",
    permissionRequired: "manageTaxonomy",
    section: "admin",
    group: "structures",
  },
  {
    id: "suggestions",
    type: "group_trigger",
    icon: <SuggestionIcon />,
    labelKey: "nav.suggestions",
    defaultLabel: "Indicações",
    path: "/suggestions",
    permissionRequired: "musicscale.performance.use",
    section: "admin",
    group: null,
  },
  {
    id: "suggest_song",
    type: "link",
    icon: <ClipboardListIcon />,
    labelKey: "nav.suggest_song",
    defaultLabel: "Indicar Música",
    path: "action:indicate",
    permissionRequired: "musicscale.performance.use",
    section: "admin",
    group: "suggestions",
  },
  {
    id: "analyze_suggestions",
    type: "link",
    icon: <SuggestionIcon />,
    labelKey: "nav.analyze_suggestions",
    defaultLabel: "Analisar Indicações",
    path: "/suggestions",
    permissionRequired: "musicscale.songs.edit",
    section: "admin",
    group: "suggestions",
  },
  {
    id: "plans",
    type: "link",
    icon: <StoreIcon />,
    labelKey: "nav.plans",
    defaultLabel: "Planos & Loja",
    path: "/plans",
    permissionRequired: "manageOrganization",
    section: "admin",
    group: null,
  },
  {
    id: "settings",
    type: "group_trigger",
    icon: <SettingsIcon />,
    labelKey: "nav.settings",
    defaultLabel: "Configurações",
    path: "/profile",
    permissionRequired: null,
    section: "admin",
    group: null,
  },
  {
    id: "my_profile",
    type: "link",
    icon: <UserIcon />,
    labelKey: "nav.my_profile",
    defaultLabel: "Meu Perfil",
    path: "/profile",
    permissionRequired: null,
    section: "admin",
    group: "settings",
  },
  {
    id: "members",
    type: "link",
    icon: <UsersIcon />,
    labelKey: "nav.members",
    defaultLabel: "Usuários",
    path: "/users",
    permissionRequired: "manageMembers",
    section: "admin",
    group: "settings",
  },
  {
    id: "roles",
    type: "link",
    icon: <KeyPermissionsIcon />,
    labelKey: "nav.roles",
    defaultLabel: "Funções",
    path: "/roles",
    permissionRequired: "manageMembers",
    section: "admin",
    group: "settings",
  },
  {
    id: "backup",
    type: "link",
    icon: <CloudArrowUpIcon />,
    labelKey: "nav.backup",
    defaultLabel: "Backup de Sistema",
    path: "/backup",
    permissionRequired: "manageOrganization",
    section: "admin",
    group: "settings",
  },
  {
    id: "plan_usage",
    type: "link",
    icon: <StoreIcon />,
    labelKey: "nav.plan_usage",
    defaultLabel: "Uso do Plano",
    path: "/plan-usage",
    permissionRequired: "manageOrganization",
    section: "admin",
    group: "settings",
  },
  {
    id: "debug_session",
    type: "link",
    icon: <BugIcon />,
    labelKey: "nav.debug_session",
    defaultLabel: "Debug Session",
    path: "/debug/session",
    permissionRequired: "manageOrganization",
    section: "admin",
    group: "settings",
  },
  {
    id: "finops_diagnostics",
    type: "link",
    icon: <ShieldAlert className="w-4 h-4 text-amber-500" />,
    labelKey: "nav.finops_diagnostics",
    defaultLabel: "Diagnóstico FinOps",
    path: "/admin/finops-diagnostics",
    // Permissions managed explicitly inside Sidebar logic based on finops diagnostics access
    permissionRequired: null,
    section: "admin",
    group: "settings",
  },

  // --- SEÇÃO AJUDA ---
  {
    id: "help_group",
    type: "group_trigger",
    icon: <HelpCircleIcon />,
    labelKey: "nav.help",
    defaultLabel: "Ajuda",
    path: "action:faq",
    permissionRequired: null,
    section: "help",
    group: null,
  },
  {
    id: "team_feedback",
    type: "action",
    icon: <MessageSquareQuestionIcon />,
    labelKey: "nav.team_feedback",
    defaultLabel: "Falar com a equipe",
    path: "action:feedback",
    permissionRequired: null,
    section: "help",
    group: "help_group",
  },
  {
    id: "faq",
    type: "action",
    icon: <BookTextIcon />,
    labelKey: "nav.faq",
    defaultLabel: "Central de Ajuda",
    path: "action:faq",
    permissionRequired: null,
    section: "help",
    group: "help_group",
  },
];
