export type StageOutputLanguage = "pt" | "en" | "es";

const copies = {
  pt: {
    output: "Saída",
    playOn: "Reproduzir em",
    thisDevice: "Este dispositivo",
    stageOutput: "Saída de Palco",
    stageOutputDescription: "Use este dispositivo para reproduzir o Pad controlado por outro aparelho.",
    receiverName: "Nome do dispositivo",
    audioOutput: "Saída de áudio",
    systemDefault: "Saída padrão do sistema",
    chooseOutput: "Escolher saída",
    refresh: "Atualizar",
    testOutput: "Testar saída",
    emergencyStop: "STOP",
    enableReceiver: "Ativar Saída de Palco",
    armAudio: "Ativar áudio",
    disableReceiver: "Desativar receptor",
    ready: "Pronto",
    notReady: "Não pronto",
    connected: "Conectado",
    offline: "Offline",
    playing: "Tocando",
    local: "Local",
    remote: "Remoto",
    noReceivers: "Nenhuma Saída de Palco disponível.",
    browserUsesSystem: "Este navegador usa a saída definida pelo sistema.",
    outputDisconnected: "A saída de áudio foi desconectada. O Pad foi interrompido por segurança.",
    receiverNotReady: "O receptor ainda não está pronto para tocar.",
    audioArmFailed: "Não foi possível armar o áudio neste dispositivo.",
    realtimeError: "A conexão da Saída de Palco foi interrompida.",
    playbackFailed: "O receptor não conseguiu reproduzir o Pad.",
    staleCommand: "Um comando antigo foi descartado por segurança.",
    openSettings: "Configurar Saída de Palco",
    sinkHint: "A saída escolhida fica salva somente neste dispositivo.",
    remoteHint: "O áudio é gerado no receptor; somente os comandos viajam pela rede.",
  },
  en: {
    output: "Output",
    playOn: "Play on",
    thisDevice: "This device",
    stageOutput: "Stage Output",
    stageOutputDescription: "Use this device to play the Pad controlled from another device.",
    receiverName: "Device name",
    audioOutput: "Audio output",
    systemDefault: "System default output",
    chooseOutput: "Choose output",
    refresh: "Refresh",
    testOutput: "Test output",
    emergencyStop: "STOP",
    enableReceiver: "Enable Stage Output",
    armAudio: "Enable audio",
    disableReceiver: "Disable receiver",
    ready: "Ready",
    notReady: "Not ready",
    connected: "Connected",
    offline: "Offline",
    playing: "Playing",
    local: "Local",
    remote: "Remote",
    noReceivers: "No Stage Output receiver is available.",
    browserUsesSystem: "This browser uses the audio output selected by the operating system.",
    outputDisconnected: "The audio output was disconnected. The Pad was stopped for safety.",
    receiverNotReady: "The receiver is not ready to play yet.",
    audioArmFailed: "Audio could not be armed on this device.",
    realtimeError: "The Stage Output connection was interrupted.",
    playbackFailed: "The receiver could not play the Pad.",
    staleCommand: "An old command was discarded for safety.",
    openSettings: "Configure Stage Output",
    sinkHint: "The selected output is stored only on this device.",
    remoteHint: "Audio is generated on the receiver; only commands travel over the network.",
  },
  es: {
    output: "Salida",
    playOn: "Reproducir en",
    thisDevice: "Este dispositivo",
    stageOutput: "Salida de Escenario",
    stageOutputDescription: "Usa este dispositivo para reproducir el Pad controlado desde otro equipo.",
    receiverName: "Nombre del dispositivo",
    audioOutput: "Salida de audio",
    systemDefault: "Salida predeterminada del sistema",
    chooseOutput: "Elegir salida",
    refresh: "Actualizar",
    testOutput: "Probar salida",
    emergencyStop: "STOP",
    enableReceiver: "Activar Salida de Escenario",
    armAudio: "Activar audio",
    disableReceiver: "Desactivar receptor",
    ready: "Listo",
    notReady: "No listo",
    connected: "Conectado",
    offline: "Sin conexión",
    playing: "Reproduciendo",
    local: "Local",
    remote: "Remoto",
    noReceivers: "No hay ninguna Salida de Escenario disponible.",
    browserUsesSystem: "Este navegador usa la salida de audio seleccionada por el sistema operativo.",
    outputDisconnected: "La salida de audio se desconectó. El Pad se detuvo por seguridad.",
    receiverNotReady: "El receptor todavía no está listo para reproducir.",
    audioArmFailed: "No fue posible preparar el audio en este dispositivo.",
    realtimeError: "La conexión de Salida de Escenario se interrumpió.",
    playbackFailed: "El receptor no pudo reproducir el Pad.",
    staleCommand: "Se descartó un comando antiguo por seguridad.",
    openSettings: "Configurar Salida de Escenario",
    sinkHint: "La salida elegida se guarda solamente en este dispositivo.",
    remoteHint: "El audio se genera en el receptor; por la red solo viajan comandos.",
  },
} as const;

export const resolveStageOutputLanguage = (language?: string | null): StageOutputLanguage => {
  const normalized = String(language || "pt").toLowerCase();
  if (normalized.startsWith("en")) return "en";
  if (normalized.startsWith("es")) return "es";
  return "pt";
};

export const getStageOutputCopy = (language?: string | null) =>
  copies[resolveStageOutputLanguage(language)];
